name: Build and Package Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    # Add UPX installation step here
    - name: Install UPX
      run: |
        sudo apt-get update
        sudo apt-get install -y upx

    - name: Build Executable with PyInstaller and UPX
      run: |
        poetry run pyinstaller --onefile --clean --upx-dir=/usr/bin cmd_line_app_pyinstaller/main.py

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable-${{ matrix.os }}
        path: |
          dist/main.exe
          dist/main
